name: road_mate_flutter
description: "A driver voice assistant app in Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.2.0
  http: ^1.2.2
  http_parser: ^4.0.2
  geolocator: ^14.0.0
  geocoding: ^4.0.0
  path_provider: ^2.1.4
  device_calendar: ^4.3.0
  shared_preferences: ^2.3.0
  timezone: ^0.9.4
  intl: ^0.20.2
  url_launcher: ^6.3.0
  permission_handler: ^12.0.1
  android_intent_plus: ^6.0.0
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^5.0.1
  youtube_transcript_api: ^1.0.0
  youtube_explode_dart: ^3.0.5
  just_audio: ^0.10.5
  audio_session: ^0.2.2
  uuid: ^4.5.2
  photo_manager: ^3.8.3
  share_plus: ^10.1.3
  image_picker: ^1.1.2
  gal: ^2.3.0
  wakelock_plus: ^1.2.11
  flutter_foreground_task: ^8.16.0
  activity_recognition_flutter: ^6.0.0
  flutter_accessibility_service:
    path: packages/flutter_accessibility_service
  workmanager: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon_square.png
    - assets/icon/app_icon_round.png
    - assets/sounds/thinking.mp3

flutter_icons:
  android: true
  ios: true
  # iPhgone
  image_path: "assets/icon/app_icon_square.png"
  remove_alpha_ios: true
  # Android
  adaptive_icon_foreground: assets/icon/app_icon_round.png
  adaptive_icon_background: "#4A90E2"  # example blue
