name: road_mate_flutter
description: "A driver voice assistant app in Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.2.0
  http: ^1.2.2
  http_parser: ^4.0.2
  geolocator: ^14.0.0
  geocoding: ^4.0.0
  path_provider: ^2.1.4
  device_calendar: ^4.3.0
  shared_preferences: ^2.3.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#0B1220"
  adaptive_icon_foreground: "assets/icon/app_icon_fg.png"  
