name: road_mate_flutter
description: "A driver voice assistant app in Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.2.0
  http: ^1.2.2
  http_parser: ^4.0.2
  geolocator: ^14.0.0
  geocoding: ^4.0.0
  path_provider: ^2.1.4
  path: ^1.9.0
  device_calendar: ^4.3.0
  shared_preferences: ^2.3.0
  sqflite: ^2.3.0
  permission_handler: ^11.3.0
  workmanager: ^0.5.2
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^16.0.0
  timezone: ^0.9.4
  intl: ^0.19.0
  url_launcher: ^6.3.0
  android_intent_plus: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon_square.png
    - assets/icon/app_icon_round.png

flutter_icons:
  android: true
  ios: true
  # iPhgone
  image_path: "assets/icon/app_icon_square.png"
  remove_alpha_ios: true
  # Android
  adaptive_icon_foreground: assets/icon/app_icon_round.png
  adaptive_icon_background: "#4A90E2"  # example blue
